### ISSUE TITLE
请问能否添加archlinuxarm支持？

### ISSUE THREAD

**Issue by showgood163** [shuopensourcecommunity/mirrors.shuosc.org#10]
from v2ex

**Comment by zhonger** [comment]
谢谢支持。镜像正在同步中，一旦一次同步完成，将在镜像站主页开放使用。

**Comment by zhonger** [comment]
目前archlinuxarm已完成一次同步，请先尝试使用一下，如果有什么问题请继续要本issue中提出。
地址： https://mirrors.shuosc.org/archlinuxarm

**Comment by showgood163** [comment]
回复晚了抱歉.
pacman -Syy测试结果正常.pacman -Syu由于早晨已经更新过所以过两天在反馈.

**Comment by showgood163** [comment]
大概20分钟前,Pacman -Syu出错,不知道为何,在https://mirrors.shuosc.org/上也并未看见arm对应的状态.

**Comment by zhonger** [comment]
由于之前archlinuxarm处于测试状态没有将信息进行公开，目前已经公开在主页镜像列表中，请查看。

**Comment by showgood163** [comment]
刚刚试了下,网站上信息可用,pacman -Syu也成功了.

**Comment by showgood163** [comment]
一分钟前测试,404错误.

**Comment by zhonger** [comment]
你好，由于系统出了问题，一个小时前正在重启修复过程中，现在已经恢复正常，可以继续测试一下。
