### ISSUE TITLE
请求添加 MacPorts 镜像

### ISSUE THREAD

**Issue by l2dy** [shuopensourcecommunity/mirrors.shuosc.org#12]
https://trac.macports.org/wiki/Mirroring
>For your initial sync, you might speed up your transfer by using a nearby existing MacPorts mirror server. For subsequent scheduled syncing, use the master rsync server, rsync-origin.macports.org.

初次同步可使用pek.cn.rsync.macports.org（清华大学开源软件镜像站）。

>You'll need a server with at least 1.5 TB of available disk space on a case-sensitive filesystem.

至少需要1.5TB的磁盘空间。

>join our existing list of mirrors

希望能加入官方镜像列表，联系方式见顶部链接。

**Comment by zhonger** [comment]
感谢提出镜像需求。由于macports占的磁盘空间比较大，目前本站暂时无法同步，在硬盘得到补充之后开始同步。

**Comment by zhonger** [comment]
macports目前正在同步中，预计在一周之内能够完成一次同步。

**Comment by zhonger** [comment]
目前macports基本已经同步完成，可以进行试用。

**Comment by l2dy** [comment]
请问有计划加入 MacPorts 官方镜像列表吗？联系方式见 https://trac.macports.org/wiki/Mirroring#Contactus 。

**Comment by zhonger** [comment]
这是个很好的建议，近期我们正筹划将镜像站的所有存储都迁移至集中式的大容量存储，待迁移完成后，我们立即着手加入 MacPorts 官方镜像列表。

**Comment by l2dy** [comment]
According to https://mirrors.shu6.edu.cn/news/p/152b0935.html, storage migration finished today.

Maybe reopen or create new issue to track progress in joining official MacPorts mirrors?

**Comment by zhonger** [comment]
Actually,  a pretty complicated problem happened in the afternoon yesterday after storage migration. The storage had taken up a lot of bandwidth of the High-Performance Computer Center, and it affects other job clusters of the HPCC. So we have migrated the storage back. It's really a pity.

And, I have a try to contact with MacPorts (macports-mgr@lists.macports.org). But the owner of macports-mgr had rejected my subscribe request. And I also have a try to email them directly, and it cannot be reached.

So, we would like to be an official MacPorts mirror if there is a way.

**Comment by l2dy** [comment]
macports-mgr is a private list, you don't have to subscribe to send emails to it.

**Comment by zhonger** [comment]
![image](https://user-images.githubusercontent.com/12064158/40246441-56323b10-5afb-11e8-923a-82b7c7747098.png)
It may be a problem in our school mail server. And I will try it again with my private mail.

**Comment by l2dy** [comment]
Please CC me (l2dy@macports.org).

**Comment by zhonger** [comment]
Ok. It sounds well. Please check the email.

**Comment by l2dy** [comment]
I received it, ~~which means the lists server received it too~~ (they are on the same server).

**Comment by zhonger** [comment]
I am so sorry. I have took a wrong email address of macports-mgr. And I have sent it again.

**Comment by l2dy** [comment]
I received this one too, and the new address is correct.

**Comment by zhonger** [comment]
It sounds good. Just wait for the reply.

**Comment by l2dy** [comment]
According to https://lists.macports.org/pipermail/macports-dev/2018-May/038884.html, please expect a reply within a week.

**Comment by zhonger** [comment]
@l2dy It has been about two weeks, and I haven't received the response from macports. Is it all right ?

**Comment by l2dy** [comment]
I pinged PortMgr (admins of MacPorts) 2 days ago and CCed you, but outlook was bouncing my mail so you didn't receive it.

PortMgr hasn't replied yet though (at least not to/CC me). I will try again so please wait patiently.

**Comment by zhonger** [comment]
It's ok. If the outlook mail bounced the mail, I suggested that you can CC to wuwozhonger@gmail.com. I can receive it.

**Comment by l2dy** [comment]
Ack. You can delete your comment now (exposing mail addresses to the public is not a good idea).

**Comment by l2dy** [comment]
PortMgr received the request, they are just too busy and did not have time to process the request.

**Comment by l2dy** [comment]
@zhonger I hope you received the mail I forwarded.

**Comment by zhonger** [comment]
@l2dy I have replied to you with email. Please do me a favor to forward that. So thanks.

**Comment by l2dy** [comment]
Are you sure you want me to forward it rather than CC them yourself?

**Comment by l2dy** [comment]
Yay! https://github.com/macports/macports-ports/commit/f3f5ddc22f2cd6b9a2c25dde29b7290766c2400e
