### ISSUE TITLE
IRC信息缺失

### ISSUE THREAD

**Issue by l2dy** [shuopensourcecommunity/mirrors.shuosc.org#13]
"在线交流 / IRC"指向Telegram链接。

**Comment by zhonger** [comment]
非常感谢你的建议。本来我们是有个wiki站点的，那里面的信息比较全面，但是目前down掉了，也在加紧修复中。一旦恢复服务就会重新链入镜像站主页。

**Comment by zhonger** [comment]
目前社区维基已经恢复，可以通过 https://wiki.shuosc.org  进行访问，对应的内容请见[联系我们](https://wiki.shuosc.org/about#联络方式)。
