### ISSUE TITLE
[mirrord] Incorrect sync info

### ISSUE THREAD

**Issue by grzhan** [shuopensourcecommunity/mirrors.shuosc.org#14]
Failed to sync `task_status.json` when mirrord service was interrupted (like `mirrors -s reload` and `mirrors -s stop`).

See: https://mirrors.shuosc.org/news/p/c97ba319.html

**Comment by ideal** [comment]
Actually it will write status info when `reload` or `stop`. Can you provide more info about the problem?

**Comment by zhonger** [comment]
@ideal Thanks for attention. Here are the details of the problem. (For `alpine` as an example)
- alpine.log
![image](https://user-images.githubusercontent.com/12064158/33199002-499eb2ea-d129-11e7-8d17-bfde00ead2ca.png)
- `mirrord -t`
![image](https://user-images.githubusercontent.com/12064158/33200904-6c4fa59e-d131-11e7-8da5-72098da9aeca.png)
Actually we can infer that the task has done from the `alpine.log`. But the task has not been over from `mirrord -t` png. There are some tasks likes this condition, such as `debian`,`pypi` and so on.
When `mirrord -s stop`, it comes like this.
![image](https://user-images.githubusercontent.com/12064158/33200951-a3e99bf4-d131-11e7-8775-29d645502f60.png)
So we do such things to restart the `mirrord` process.
```bash
mirrord 
mirrord -t
```
It comes on common. But the status code of the tasks which are interrupted in the `task_status.json`  have not been changed. Like this:
![image](https://user-images.githubusercontent.com/12064158/33201134-3b79086a-d132-11e7-8049-a235a9e801b6.png)
(url: https://mirrors.shuosc.org/status/task_status.json )
Here is the result of `mirrord -t`.
![image](https://user-images.githubusercontent.com/12064158/33201187-6b7e1172-d132-11e7-83f1-388a6c1c697e.png)

Thanks for attention again.

**Comment by ideal** [comment]
To first problem, did you set `twgostage=1` in mirror.ini for alpine, debian and pypi?

And another problem, `mirrord -s stop` shows that it failed killing the process (pid 20417, which is read from ~/.config/mirror/mirrord.pid)，so did you killed the mirrord process before you run `mirrord -s stop` with some commands like `kill -9 20417`. If so, mirrord have no chance to update status files. If not, maybe mirrord is killed by the system with strange reason, but that need more logs to analyse (/var/log/mirrord/mirrord.log and /var/log/messages).

So you can check you mirror.ini. And try analysing /var/log/mirrord/mirrord.log and /var/log/messages for some clues. If that is the problem of mirror application, i can help to fix.

**Comment by zhonger** [comment]
To first proble, `twgostage=0` are in mirror.ini for alpine,debian adn pypi, because `firststage` is not set.

Another problem, I have never killed the mirrord process before `mirrord -s stop`. So I have checked the `/var/log/mirrord/mirrord.log` and `/var/log/messages`. There is nothing helpful in `/va/log/messages`. And here are some snippets in  `/var/log/mirrord/mirrord.log` what I think it's helpful.
![image](https://user-images.githubusercontent.com/12064158/33205779-233be91e-d143-11e7-8068-c0acd7d4c269.png)
It happens when I do `mirrord -s stop` and `mirrord`.
I don't know whether it can be helpful for you to find something. If there are something more you need, please let me know.

**Comment by ideal** [comment]
Sorry that is a bug of mirrord in old versions. Some times `sleeptime` may be less than zero and so it gets an IOError which cause mirrord to exit. https://github.com/ideal/mirror/blob/master/mirror/scheduler.py#L106

Did you installed mirror from pip? If so, you can `pip uninstall mirror`, then clone a git repo of mirror and run `python2 setup.py build` and `sudo python2 setup.py install` to install the current version. For safety, you can backup your `~/.config/mirror` before you do anything!

If you still have other problems, please contact me.

**Comment by zhonger** [comment]
I have checked the mirror version. It's 0.6.8 and it's likely not an old version. And I install the mirror with `python2 setup.py build` and `sudo python2 setup.py install`. And the version is `0.6.6`.
It occurs a new problem. 
```bash
pkg_resources.DistributionNotFound: The 'mirror==0.6.8' distribution was not found and is required by the application
```
So maybe the reason is not clear.

**Comment by ideal** [comment]
Sorry the version problem is because that when i uploaded mirror to pip, I uploaded twice to fix a problem, but version number can not be same, so i change a version to 0.6.8 in pip.

Version in the source code still is 0.6.6, I fixed some problems in master branch but did not update the version number yet.

So did you run `pip uninstall mirror`?

**Comment by zhonger** [comment]
Yes, I run `pip uninstall mirror` firstly, and then do the install with source code. 
So I have known why distribution was not found.

**Comment by ideal** [comment]
However if you have run `pip uninstall mirror`  before you install it from git repo, `/usr/bin/mirrord` should be updated, it will look for 0.6.6, not 0.6.8.

Could you verify the content and its ctime of `/usr/bin/mirrord` ?

**Comment by ideal** [comment]
I have created a new version 0.7.0 and uploaded it to PYPI.

Can you try to upgrade it through pip?

**Comment by zhonger** [comment]
Yes, I have a try to upgrade it to `0.7.4`. And I change the version in `/usr/bin/mirrord` to `0.7.4`. The `mirror` has been installed successfully. But it occurs the same problems again like the first description except that `mirrord -s stop` is successful.

**Comment by zhonger** [comment]
@ideal We are so happy you can help us to fix this problem. And we want to invite you to our qq group or telegram to do more exchange talks if you would not mind. Our qq group number is 24061199. Our telegram join link is  https://t.me/joinchat/ErK1eQ6s9-axpVr75Oiwww .  

Thanks so much!

**Comment by ideal** [comment]
![image](https://user-images.githubusercontent.com/261698/33301223-41570720-d3ba-11e7-90c0-04ed3f7705c3.png)

Seems that debian is set with twostage, when first stage finished, it will not update status, because the task is not finished yet.

And here debian task is killed by timeout checking, so you can set a longer timeout parameter for it.

**Comment by zhonger** [comment]
@ideal  I have reboot the server yesterday, and do something according to what you say.
When I kill the `mirror` main progress by `kill -9` and remove the `task_status.json`, it starts again and seems ok. `mirrord -s stop` can stop all `mirror` progress and interrupt the task progress. And the status code and exitcode of the task have changed.
Something more, the debian task's timeout parameter is `12h`. I think it's enough. 
Things go well. So I think it may be a fault for the server's long live.

**Comment by zhonger** [comment]
@ideal We are so sorry to tell you that, we decided to abandon the `mirror` tool after lots of discussions inside the community. The `mirror` tool is very useful for us to keep the mirror site alive for a long time. So we are so grateful to you and your help when we are in trouble. What's more, our server operating system is `CentOS 6` and it's too old. We want to use `Docker` to manage kinds of runtime environments and make the server operation more standardized. Now we want to choose an existing mirror tool with docker (like `tunasync`) or start a project with docker based your `mirror` tool. Considering our complex storage distribution, we prefer to choose the latter. Meanwhile, we also want to get your help sometime later.

Thanks a lot.

**Comment by ideal** [comment]
@zhonger OK. If there is anything I can help in the future, I am glad to :)
