### ISSUE TITLE
jenkins的git插件无法连接(找不到页面)

### ISSUE THREAD

**Issue by abysscat-yj** [shuopensourcecommunity/mirrors.shuosc.org#22]
rt

**Comment by zhonger** [comment]
请允许我调查一下，如果你有报错的相关截图方便提供，那就更好了。

**Comment by zhonger** [comment]
经过调查，发现是由于Nginx使用了 `/git/` 目录作为`git项目镜像`的前缀，导致`Jenkins`中的`git`目录无法正常被访问。现已通过调整前缀解决了该问题，请重新尝试一下。

**Comment by abysscat-yj** [comment]
ok，能成功访问了，谢谢啦
