### ISSUE TITLE
[Mirror Architecture] 镜像站调整讨论

### ISSUE THREAD

**Issue by zhonger** [shuopensourcecommunity/mirrors.shuosc.org#23]
上海大学开源镜像站自2017年11月在V2EX上正式对外公开以来，很多国内外的开发者都选择了本镜像站。起初人还不多的时候，大家用的还是蛮开心的。随着镜像站相继成为各大开源操作系统、软件的官方镜像源，镜像站的流量变得很大，用户体验也有所下降。通过一些简单的Nginx设置、物理网络设置、镜像同步任务分散等举措，镜像站的可用性也得到了一定的提升，在问题发现后可以很快恢复。但是一些旧有的问题还是没有得到根本的解决，比如说采用NFS存储直接提供HTTP、FTP、RSYNC服务，当NFS存储失联后，HTTP请求出现无法响应，并反复请求NFS存储目录造成服务器I/O过大，从而导致镜像站无法访问。

今年4月下旬，由高效能计算中心支持的集中式存储终于到位，目前分配给开源社区的容量为40T（后续可继续增加容量配额），并提供了两台配有SSD的中等配置虚拟机（8核16G）。

为了进一步提高镜像站的可用性、可靠性以及开源社区其他各项服务的科学运维管理，特别创建本issue将镜像站调整方案进行公布，欢迎各位关心开源社区和镜像站的大佬们提提看法或者建议。

### 镜像站架构
以下为镜像站物理架构图：
![image](https://user-images.githubusercontent.com/12064158/39466100-b7658216-4d59-11e8-91d8-ca2a422dd63e.png)

#### 域名和资源整合

1. 将OSC主站、wiki、blog整合到osc.shu.edu.cn域名下

- [x] https://osc.shu.edu.cn  ---- OSC主站 (拟采用Jenkins自动部署)
- [x] https://osc.shu.edu.cn/wiki/ ---- 社区维基（docker化，目前部署在https://wiki.shuosc.org）
- [x] https://osc.shu.edu.cn/blog/ ---- 微信归档 （拟采用Jenkins自动部署，目前部署在https://blog.shuosc.org）

2. 将镜像站的内容整合到mirorrs.shu(6).edu.cn域名下

- [x] https://mirrors.shu.edu.cn ---- 镜像站
- [x] https://mirrors.shu.edu.cn/help/ ---- 帮助文档（gitbook生成，拟采用Jenkins自动部署）
- [x] https://mirrors.shu.edu.cn/news/ ---- 镜像通知（hexo生成，拟采用Jenkins自动部署）
- [x] https://mirrors.shu.edu.cn/repos/ ---- 镜像配置生成工具（@AdrianDuan开发，拟采用Jenkins自动部署）
- <del> https://mirrors.shu.edu.cn/ip/ ---- IP定位服务（待开发，docker化  or [fcambus/telize](https://github.com/fcambus/telize)）</del> (延期开发)

3. 建议将 [Shuhelper](https://shuhelper.cn) 和 [SHUer.link](https://shuer.link) docker化之后迁移到 lenovo
4. `shuosc.org` 域名下采用 **Let's sencrypt** 提供的泛域名证书 （已部署）
5. NPM、Maven、Docker镜像加速服务 （尚未对外开放）

#### 镜像可用性、可靠性提升
1. 建立前后端代理缓存机制
将langchao作为gateway，采用 squid 代理所有镜像的 HTTP、FTP、RSYNC请求。NFS只用于必要的镜像同步任务，不再用于提供HTTP、FTP、RSYNC服务.
2. 将自强4000机房的40T存储和学院托管机房的14T存储作为主要存储空间，langchao上只留有一些限制同步请求ip的镜像，lenovo上不保留任何镜像存储.
3. 高可用负载均衡
优先使用自强4000存储提供对外访问，当访问不到内容或访问请求过多时将请求切换到学院托管机房存储访问.
4. 自强4000机房的虚拟机借助SSD硬盘提供主动缓存策略提升访问速度.

**Comment by l2dy** [comment]
Will the "dual-stack" (A/AAAA) mirror domain be migrated to shu.edu.cn?

**Comment by zhonger** [comment]
@l2dy Your suggestion is good. But it can't work because the authoritative DNS server of `shu.edu.cn` just supports the A record and the AAAA record is all in the authoritative DNS server of `shu6.edu.cn`. It's an unsolvable problem. So we still use `mirrors.shuosc.org` to support A/AAAA record resolution. 

And the ipv6 of Shanghai University is unstable. So we suggest our users to using a single domain.
