### ISSUE TITLE
能否添加个KaOS的源？

### ISSUE THREAD

**Issue by HussonProject** [shuopensourcecommunity/mirrors.shuosc.org#24]
能否添加个KaOS的源？
kaosx.us

**Comment by AdrianDuan** [comment]
KaOS已经加入镜像同步任务中，待同步完成后会对外开放，请注意关注网站通知

**Comment by HussonProject** [comment]
多谢！

**Comment by HussonProject** [comment]
不需要这么久吧？还是你们放假要等下学期？或者你们需要审批之类的？

**Comment by zhonger** [comment]
@HussonProject 请稍安勿躁，由于近期学校供电线路调整，新增同步镜像工作进度有点慢，现已从princeton 镜像节点同步 kaoslinux 镜像，估计在明天早些时候就可以开放使用。

**Comment by zhonger** [comment]
@HussonProject kaoslinux 镜像已同步完毕并开放使用，Happy Coding.
