### ISSUE TITLE
建议删除ubuntu-security

### ISSUE THREAD

**Issue by wuchengjie** [shuopensourcecommunity/mirrors.shuosc.org#26]
贵站于黑五添加的ubuntu-security镜像其实是没必要的。因为security.ubuntu.com和archive.ubuntu.com是完全一样的，ubuntu默认将xxx-security单独弄一个security.ubuntu.com是为了防止镜像源同步失败造成用户无法及时获取安全更新。所以建议贵站删除ubuntu-security以节约硬盘空间。

refs: https://askubuntu.com/questions/185317/are-security-ubuntu-com-updates-eventually-merged-into-normal-updates/185444#185444

**Comment by zhonger** [comment]
@wuchengjie 感谢你的关注和反馈，根据帖子的意思的确是如此。为了节约硬盘空间，我们决定在12月20日八点删除`ubuntu-security`镜像。届时我们会提前在镜像站预先通知。再次表示感谢。
