### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by jihaonew** [shuopensourcecommunity/mirrors.shuosc.org#3]
啥时候会有tensor flow的呢？

**Comment by zhonger** [comment]
你好！Tensorflow现在无须单独镜像，在镜像站的Pypi库中可以直接`pip3 install tensorflow` 或者 `pip3 install tensorflow-gpu` 安装，有关于Pypi镜像的详细帮助请见https://wiki.shuosc.org/help/pypi (目前帮助站点处于维护状态，请在晚些时候访问)

**Comment by jihaonew** [comment]
有镜像会快一点吗？pip安装的话真慢诶，清华镜像是有tensor flow的，不过没有Windows的，今天在Windows上装TF的时候直接用pip，也太慢啦！ 在2017年09月29日 15:40 ，Mr Li写道： 你好！Tensorflow现在无须单独镜像，在镜像站的Pypi库中可以直接pip3 install tensorflow 或者 pip3 install tensorflow-gpu 安装，有关于Pypi镜像的详细帮助请见https://wiki.shuosc.org/help/pypi (目前帮助站点处于维护状态，请在晚些时候访问) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zhonger** [comment]
目前镜像站提供Pypi镜像镜像，在windows平台下，请在用户主目录下新建`.pip`文件夹，并在文件夹中新建配置文件`pip.ini`，文件内容如下：
```
[global]
index-url=https://pypi.shuosc.org/simple
[list]
format=columns
```
按照以上配置即可使用镜像站提供的Pypi镜像安装pip库。如果修改了pypi源到本站提供的镜像后速度还是很慢的话，建议你使用有线网络尝试。一般来说，校内即使是无线网，pip的速度也会有200k/s以上。如果你采用的是`python2`安装失败的话，建议你采用`python3`的`pip3`安装`TensorFlow库`

**Comment by jihaonew** [comment]
Thanks.
