### ISSUE TITLE
VSCode镜像同步滞后

### ISSUE THREAD

**Issue by thezzisu** [shuopensourcecommunity/mirrors.shuosc.org#32]
VSCode镜像严重滞后

SHU上只到2018-11-16 08:44

官方源已经到15-Mar-2019 17:46了

**Comment by zhonger** [comment]
感谢反馈，由于VSCode镜像同步方式采用的是wget直接拉取方式，且VSCode更新比较频繁，本站为了避免给上游微软VSCode服务造成不必要的I/O，目前采用的是大版本更新策略，因此有所滞后。现在后台将进行一次最新版本的拉取。这一问题的完全解决需要依赖重新构建新的镜像同步方式，目前也在研发中，敬请期待。

**Comment by zhonger** [comment]
@ZhangZisu 目前VSCode镜像已经同步完毕，欢迎继续使用。

**Comment by thezzisu** [comment]
谢谢，建议定期check一下上游的包列表，增量同步
