### ISSUE TITLE
开源社区挂了吗？什么时候能恢复？

### ISSUE THREAD

**Issue by FrostbiteXSW** [shuopensourcecommunity/mirrors.shuosc.org#34]

**Comment by zhoudian64** [comment]
不好意思，由于**不可抗**政策因素，上海大学开源社区提供的镜像站将对**外网**无限期暂停访问，在校园内使用校园网则可以以最高的速度访问到镜像站。本社区最近有一直在开发新的对校园内的**合法合规**服务，和对外开展各种技术分享活动，可以关注「微信公众号」**_SHU开源社区_**查看最新活动。

**Comment by FrostbiteXSW** [comment]
我是本校校园网来着，打不开镜像站，提示找不到IP地址，我的物理位置是东区计算机楼，访问域名是http://mirrors.shuosc.org/，是因为域名错了吗？

**Comment by zhoudian64** [comment]
很不巧，由于另一项互联网相关法律法规，.org域名都不能备案了，只能使用http://mirrors.shu.edu.cn/ ，了

**Comment by FrostbiteXSW** [comment]
而且还不能用tls，不过总算是上去了，谢谢大佬
