### ISSUE TITLE
暂时停止服务通知

### ISSUE THREAD

**Issue by longfangsong** [shuopensourcecommunity/mirrors.shuosc.org#35]
应上级要求，镜像站机器需要搬迁，故暂时停止服务。
何时恢复服务请等待通知。

**Comment by zhoudian64** [comment]
现恢复校内访问，可以使用了，部分源可能出现同步问题，请在web端查看同步状态。

**Comment by zhonger** [comment]
现已完全恢复，访问方式如下：

（镜像站）  http://mirrors.shu.edu.cn (校园网，IPv4)
（Docker镜像加速） http://docker.mirrors.shu.edu.cn （校园网，IPv4）
（镜像站） https://mirrors.shuosc.cn （校园网，IPv4；公网，IPv6）
（镜像站） https://mirrors6.shu.edu.cn （公网，IPv6）
（Docker镜像加速） https://docker.mirrors6.shu.edu.cn （公网，IPv6）

欢迎使用。
