### ISSUE TITLE
希望添加Parrot Security OS镜像

### ISSUE THREAD

**Issue by Lodour** [shuopensourcecommunity/mirrors.shuosc.org#4]
**项目：** [Parrot Security OS](https://www.parrotsec.org)
**官方镜像：** http://deb.parrotsec.org/parrot
**镜像列表：** https://docs.parrotsec.org/doku.php/mirrors-list
**其他国内镜像：** [USTC](http://mirrors.ustc.edu.cn/parrot/), [TUNA](https://mirrors.tuna.tsinghua.edu.cn/parrot/)

谢谢~

**Comment by zhonger** [comment]
你好！

感谢你提交了`Parrot Security OS`镜像源添加的请求，开源社区已经接受你的提议，并正在进行同步过程。一旦同步全部完成，将开放使用。在此期间，请你暂时仍使用USTC或TUNA提供的镜像源，如果开放使用了，你会第一时间得到通知。

祝好！

**Comment by zhonger** [comment]
@Lodour `Parrot`镜像源目前已完成一次完整同步，你可以通过 https://mirrors.shuosc.org/parrot 进行访问。在使用过程中有任何问题请在本Issue继续提出。谢谢。

**Comment by Lodour** [comment]
谢谢~
