### ISSUE TITLE
希望有msys2的镜像

### ISSUE THREAD

**Issue by missdeer** [shuopensourcecommunity/mirrors.shuosc.org#5]
RT

**Comment by zhonger** [comment]
谢谢支持，msys2目前已经在从清华大学tuna提供的源开始同步过来，等待同步完成后再从官方同步，一旦同步完成，将会通知开放使用。

**Comment by zhonger** [comment]
目前msys2已完成一次同步，可以先尝试使用一下，有问题的话请在本issue继续回复。
地址： https://mirrors.shuosc.org/msys2/
