### ISSUE TITLE
镜像增加申请

### ISSUE THREAD

**Issue by sicifus** [shuopensourcecommunity/mirrors.shuosc.org#6]
弱弱提个建议，既然有 openwrt 了，能否再加上 entware 的源？谢谢～

**Comment by zhonger** [comment]
谢谢支持，目前正在根据你的请求进行相关信息的调研，如果你已知晓烦请告知，在此期间请耐心等待。

**Comment by zhonger** [comment]
经过调查，发现了一条有趣的issue https://github.com/Entware-ng/Entware-ng/issues/292 ，请查看一下。entware目前只能通过proxy的方式进行访问，无法镜像。
