### ISSUE TITLE
望能添加CENTOS的ARM源

### ISSUE THREAD

**Issue by xiaodaowanwan** [shuopensourcecommunity/mirrors.shuosc.org#9]
我用的树莓派，国内好像没有专门的源哦

**Comment by zhonger** [comment]
已调查清楚CentOS所开放的arm源地址为 http://mirror.centos.org/altarch/ ，尚未具体了解占的空间，待仔细调查好决定是否镜像，烦请等待。如源地址有误，请回复说明。

**Comment by zhonger** [comment]
altarch目前已在同步中，一旦完成一次同步，即可开放使用。

**Comment by zhonger** [comment]
目前altarch已经完成了一次同步，请尝试使用一下。如果有什么问题，请继续在本issue中提出。
地址： https://mirrors.shuosc.org/centos-altarch
